meta_product_name: "Chrysalis"
meta_title: "Chrysalis - Transforming and Aiding Society"
meta_description: "Chrysalis aids users in reentering society through encouraging and supporting them through actionable steps. As Japan's only app for the hikikomori phenomenon, we want to transform society so that you will never be left behind again."
meta_image: "cover.png"
